<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Imovel;
/**
 * ImovelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImovelRepository extends \Doctrine\ORM\EntityRepository
{

    public function save(Imovel $imovel) {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($imovel);
        $entityManager->flush();
    }
}
